ALTER TABLE tarifa
    ADD CONSTRAINT fk_tarifa_sucursal
        FOREIGN KEY (id_sucursal)
        REFERENCES sucursal (id_sucursal)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    ADD CONSTRAINT fk_tarifa_tipo
        FOREIGN KEY (id_tipo)
        REFERENCES tipo_vehiculo (id_tipo)
        ON UPDATE CASCADE
        ON DELETE RESTRICT;
